name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chess
          pip install pygame
          pip install pytest
      - name: Test with pytest
        run: |
          cd windows 
          python -m pytest test_ioDriver.py
          echo "Leute meine Mutter hat mir einfach erlaubt, dass ich mir wieder eine Cola kaufen darf! :D Ich hatte aber leider nicht genug Geld und hab mir leider nur eine "Ja!"-Cola gekauft. :( Aber jetzt kann ich Cola trinken und Trios zocken! :D YIPPYYYYYYYY!!!!!"